name: flutter_exoplayer_example
description: Demonstrates how to use the flutter_exoplayer plugin.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+17
  path_provider: ^1.2.0
  flutter_exoplayer:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
